name: deploy

on:
  push:
    branches:
    - main

jobs:
  main:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Quay
        run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_SECRET }}" quay.io
      - name: Push image to Quay
        run: make IMAGE_TAG=main push
