name: deploy

on:
  push:
    branches:
    - main
  release:
    types: [published]

jobs:
  main:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Push image to Quay
        run: make IMAGE_TAG=main push
  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to quay.io
      #   uses: docker/login-action@v1
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USER }}
      #     password: ${{ secrets.QUAY_TOKEN }}
      - name: Push image to Quay
        run: echo ${{ github.event.tag }}
