name: sanity

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    branches:
    - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - name: Run verification checks
        run: make verify
